frase = str(input("Digite uma frase: "))
frase = frase.replace("a","*")
frase = frase.replace("e","*")
frase = frase.replace("i","*")
frase = frase.replace("o","*")
frase = frase.replace("u","*")
print("Frase modificada: %s" % (frase))